"""Regenerate web/vendor/lucide-icons.js with the Lucide icons the UI uses.

Icon names are the quoted strings in web/app.js that are Lucide icon names, so using icon('name') in app.js and
re-running this is all it takes to add one.

    npm pack lucide-static && tar xzf lucide-static-*.tgz && python3 tools/build_icons.py package
"""
import json
import pathlib
import re
import sys
import xml.etree.ElementTree as ET

ROOT = pathlib.Path(__file__).resolve().parent.parent


def main(pkg):
    pkg = pathlib.Path(pkg)
    version = json.loads((pkg / "package.json").read_text())["version"]
    used = set(re.findall(r"'([a-z0-9-]+)'", (ROOT / "web" / "app.js").read_text()))
    names = sorted(n for n in used if (pkg / "icons" / f"{n}.svg").exists())
    icons = {n: [[el.tag.split("}")[-1], dict(el.attrib)] for el in ET.parse(pkg / "icons" / f"{n}.svg").getroot()] for n in names}
    license_text = (pkg / "LICENSE").read_text().strip().replace("*/", "* /")
    out = ROOT / "web" / "vendor" / "lucide-icons.js"
    out.write_text(f"/*! Lucide icons (lucide-static {version}), subset generated by tools/build_icons.py.\n"
                   f"{license_text}\n*/\nwindow.LUCIDE = {json.dumps(icons, separators=(',', ':'))};\n")
    print(f"{len(names)} icons -> {out.relative_to(ROOT)}")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "package")
